# Generated by Django 4.0.4 on 2022-05-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('caption', models.CharField(max_length=20)),
                ('header_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
