# Generated by Django 4.0.4 on 2022-05-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='header_image',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='test', upload_to='img/%y'),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(max_length=100),
        ),
    ]
